from . import crm_lead
from . import ai_scoring_config
from . import ai_scoring_detail
from . import name_scorer
from . import customer_scorer
from . import address_scorer
from . import website_scorer
from . import email_scorer
from . import job_position_scorer
from . import phone_scorer
from . import mobile_scorer
from . import internal_notes_scorer